### ISSUE TITLE
1주차 페어 코드 리뷰

### ISSUE THREAD

**Issue by yzpocket** [JJW11111/Spring_week01#1]
- Restful한 설계를 잘 했나요?
네, 각 기능마다 (POST, GET, PUT, DELETE) 메소드를 적절히 사용했으며,
요청 메서드의 매개변수 또한 @PathVariable, @RequestParam을 적절하게 사용했습니다.

- API 명세서에 따른 설계가 잘 되어있나요?
네, 명세서와 API의 구성이 동일합니다.
다만, API 명세서를 확인할 수 있는 방법이 없어서, 앞으로는 항상 API 명세서를 작성하고, 또는 예제에서 제공된다면,
그 부분을 Github 메인 페이지에서 볼 수 있도록 해주시면 좋을것 같습니다.

- 예외처리가 미흡한 부분은 없나요?
예외처리는 정확하게 되어있습니다. 오히려 제가 이 예외 처리 방식을 참고하여, 제 프로젝트에서도 적용시켜보도록 노력하겠습니다.

ps. 추가적으로 Github의 커밋 관리가 필요해 보입니다.

**Comment by JJW11111** [comment]
> * Restful한 설계를 잘 했나요?
>   네, 각 기능마다 (POST, GET, PUT, DELETE) 메소드를 적절히 사용했으며,
>   요청 메서드의 매개변수 또한 @PathVariable, @RequestParam을 적절하게 사용했습니다.
> * API 명세서에 따른 설계가 잘 되어있나요?
>   네, 명세서와 API의 구성이 동일합니다.
>   다만, API 명세서를 확인할 수 있는 방법이 없어서, 앞으로는 항상 API 명세서를 작성하고, 또는 예제에서 제공된다면,
>   그 부분을 Github 메인 페이지에서 볼 수 있도록 해주시면 좋을것 같습니다.
> * 예외처리가 미흡한 부분은 없나요?
>   예외처리는 정확하게 되어있습니다. 오히려 제가 이 예외 처리 방식을 참고하여, 제 프로젝트에서도 적용시켜보도록 노력하겠습니다.
> 
> ps. 추가적으로 Github의 커밋 관리가 필요해 보입니다.

넵 감사합니다. 조언 감사합니다~!
