### ISSUE TITLE
코드 리뷰 - 최선강 기술 매니저

### ISSUE THREAD

**Issue by zzangoobrother** [JJW11111/Spring_week01#2]
안녕하세요. 과제 하시느라 수고하셨습니다.

1. BlogService 에서 조회하는 메소드에 @transactional(readOnly = true) 를 사용하시면 성능에 이점이 있습니다. 왜 성능에 이점이 있는지 한번 공부해보시면 좋습니다.
2. https://github.com/JJW11111/Spring_week01/blob/308173c5907a4497236372948baed39da54ff7bf/src/main/java/com/sparta/blog/service/BlogService.java#L50
비밀번호 비교는 도메인에 메소드를 만들어 비교하는게 조금 더 객체지향적이고 도메인에 비즈니스를 응집시켜 좋습니다.

다음 과제도 화이팅 하세요.

**Comment by JJW11111** [comment]
넵 감사합니다!
